version: '3.8'

services:

  # Redis — for rate limiting
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  # FGW Service
  fgw-service:
    build: .
    container_name: fgw-service
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      # Redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # AWS (from your local AWS credentials)
      AWS_REGION: us-east-1
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
    restart: always